# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.4.0-rc3"
rotrieve = "roblox/rotriever@0.5.12"
tarmac = "roblox/tarmac@0.7.0"
lune = "filiptibell/lune@0.7.11"