[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
rotrieve = { source = "roblox/rotriever", version = "0.5.1" }
tarmac = { source = "roblox/tarmac", version = "0.7.0" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
