[package]
name = "FactoriesPlugin"
version = "0.1.0"
authors = ["Dustin Haynes <dhaynes@roblox.com>"]
license = "Proprietary"
content_root = "src"

# Optional fields and their definitions can be found at:
# https://pages.github.rbx.com/pdoyle/rotriever-docs/reference/manifest-format/#manifest-fields

[dependencies]
# Different kinds of dependencies are specified in different ways. See more details at:
# https://pages.github.rbx.com/pdoyle/rotriever-docs/reference/manifest-format/#specifying-manifest-dependencies
AssessmentUI = "github.com/imbellus2/assessment-ui@3.0.0"
FishBlox = "https://github.com/imbellus2/fishblox@6.0.51"
Dash = "github.com/roblox/dash@0.1.7"
Roact = { target = "github.com/roblox/roact-alignment", version = "17.0.1-rc.11", package = "RoactCompat" }
React = "github.com/roblox/roact-alignment@17.0.1-rc.11"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.11"
Rodux = "github.com/Roblox/rodux@3.0.0"
RoactRodux = "github.com/Roblox/roact-rodux@0.5.0"
Utilities = "github.com/imbellus2/assessment-utils@3.0.5"
